#!/usr/bin/env bash
export BOILERPLATE_ENV="PROD"

# App 
export DEFAULT_FRIENDLY_APP_NAME="Sample"
export DEFAULT_FRIENDLY_COMPANY_NAME="Company"

# Sonarqube
export DEFAULT_SHOULD_USE_SONAR=true
export DEFAULT_FRIENDLY_SONARQUBE_URL="localhost"
export DEFAULT_FRIENDLY_SONARQUBE_PORT="9001"
